let pages = {
  "archives_olds": {title: "", description:"", image: "", slug:""},
  "articlecontents": {title: "title", description:"article", image: true, slug:"/articles/"},
  "assopages": {title: "", description:"", image: "", slug:""},
  "credited_images": {title: "", description:"", image: "", slug:""},
  "ecoles": {title: "", description:"", image: "", slug:""},
  "festivalpages": {title: "", description:"", image: "", slug:""},
  "festivals": {title: "", description:"", image: "", slug:""},
  "festivals__spectacles": {title: "", description:"", image: "", slug:""},
  "general_menus": {title: "", description:"", image: "", slug:""},
  "global_menus": {title: "", description:"", image: "", slug:""},
  "home_display_tabs": {title: "", description:"", image: "", slug:""},
  "homepages": {title: "", description:"", image: "", slug:""},
  "hors_scene_pages": {title: "", description:"", image: "", slug:""},
  "hors_scene_tabs": {title: "", description:"", image: "", slug:""},
  "infopratiques": {title: "", description:"", image: "", slug:""},
  "menu_headers": {title: "", description:"", image: "", slug:""},
  "news_pages": {title: "", description:"", image: "", slug:""},
  "newspages": {title: "", description:"", image: "", slug:""},
  "newstabs": {title: "", description:"", image: "", slug:""},
  "paroles": {title: "", description:"", image: "", slug:""},
  "partnerpages": {title: "", description:"", image: "", slug:""},
  "scolaires": {title: "", description:"", image: "", slug:""},
  "seminaires": {title: "", description:"", image: "", slug:""},
  "spectacles": {title: "title", description:"info", image: true, slug:"/spectacle/"},
  "transmissions": {title: "", description:"", image: "", slug:""},
  "webradios": {title: "", description:"", image: "", slug:""}
};
module.exports = pages;
